typeidea/typeidea/urls.py
#import xadmin
from rest_framework.routers import DefaultRouter
from rest_framework.documentation import include_docs_urls
from django.conf import settings
from django.contrib import admin
from django.urls import path,re_path,include
from django.contrib.sitemaps import views as sitemap_views
from django.conf.urls.static import static
from django.views.static import serve

from blog.views import (
    post_list,post_detail,
    IndexView,CategoryView,TagView,
    PostDetailView,SearchView,AuthorView,
)
from config.views import LinkListView
from comment.views import CommentView,VerifyCaptcha
from .custom_site import custom_site
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
from .autocomplete import CategoryAutocomplete,TagAutocomplete
from blog.apis import PostViewSet,CategoryViewSet
from django.views.decorators.cache import cache_page

router=DefaultRouter()
router.register(r'post',PostViewSet,basename='api-post')
router.register(r'category',CategoryViewSet,basename='api-category')

'''
url(r'^', include(router.urls)),
url(r'^api/', include((router.urls, 'app_name'))),
url(r'^api/', include((router.urls, 'app_name'), namespace='instance_name')),
'''

urlpatterns = [
    re_path(r'^admin_tools/', include('admin_tools.urls')),
    path('super_admin/', admin.site.urls,name='super-admin'),
    path('admin/', custom_site.urls,name='admin'),
    #path('xadmin/', xadmin.site.urls,name='xadmin'),

    path('',IndexView.as_view(),name='index'),
    path('category/<int:category_id>/',CategoryView.as_view(),name='category-list'),
    path('tag/<int:tag_id>/',TagView.as_view(),name='tag-list'),
    path('post/<int:post_id>/',PostDetailView.as_view(),name='post-detail'),
    path('search/',SearchView.as_view(),name='search'),
    path('author/<int:owner_id>/',AuthorView.as_view(),name='author'),
    path('links/',LinkListView.as_view(),name='links'),
    path('comment/',CommentView.as_view(),name='comment'),
    re_path(r'^rss|feed/', LatestPostFeed(), name='rss'),
    #re_path(r'^sitemap\.xml$', sitemap_views.sitemap, {'sitemaps': {'posts': PostSitemap}}),
    re_path(r'^sitemap\.xml$',cache_page(60*20,key_prefix='sitemap_cache_')( sitemap_views.sitemap ), {'sitemaps': {'posts': PostSitemap}}),
    path('category-autocomplete/', CategoryAutocomplete.as_view(), name='category-autocomplete'),
    path('tag-autocomplete/', TagAutocomplete.as_view(), name='tag-autocomplete'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    #path('api/post/',post_list,name='post-list'),
    #path('api/post/',PostList.as_view(),name='post-list'),

    #path('api/', include(router.urls,namespace='api')),无效

    path('api/', include((router.urls, 'blog'), namespace='api')),
    #path('api/', include((router.urls, 'blog'))),
    #path('api/', include(router.urls)),

    path('api/docs/',include_docs_urls(title='typeidea apis')),
    re_path(r'^static/(?P<path>.*)$',serve,{
        'document_root': settings.STATIC_ROOT,
    }),
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
    path('captcha/', include('captcha.urls')),
    path('verify_captcha/', VerifyCaptcha.as_view(), name='verify_captcha'),
    ]
#static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        #path('__debug__/', include(debug_toolbar.urls)),
        path('silk/', include('silk.urls',namespace='silk')),
    ] + urlpatterns

typeidea/comment/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    target = models.CharField(max_length=100, verbose_name="评论目标")
    content = models.CharField(max_length=2000, verbose_name="内容")
    nickname = models.CharField(max_length=50, verbose_name="昵称")
    website = models.URLField(verbose_name="网站")
    email = models.EmailField(verbose_name="邮箱")
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name="状态")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name = verbose_name_plural = "评论"

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

typeidea/comment/forms.py
from mistune import markdown
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    email = forms.CharField(
        label='Email',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    website = forms.CharField(
        label='网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )

    content = forms.CharField(
        label="内容",
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={'rows': 6, 'cols': 60, 'class': 'form-control'}
        )
    )

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) < 10:
            raise forms.ValidationError('内容长度怎么能这么短呢！！')
        content = markdown(content)
        return content

    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

typeidea/comment/views.py
from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url
from django.http import JsonResponse
from django.shortcuts import redirect
from django.utils import timezone
from django.views.generic import TemplateView, View

from .forms import CommentForm


# Create your views here.
class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target
            instance.save()
            succeed = True
            return redirect(target)
        else:
            succeed = False

        context = {
            'succeed': succeed,
            'form': comment_form,
            'target': target,
        }
        return self.render_to_response(context)

class VerifyCaptcha(View):
    def get(self, request):
        captcha_id = CaptchaStore.generate_key()
        return JsonResponse({
            'captcha_id': captcha_id,
            'image_src': captcha_image_url(captcha_id),
        })

    def post(self, request):
        captcha_id = request.POST.get('captcha_id')
        captcha = request.POST.get('captcha')
        captcha = captcha.lower()

        try:
            CaptchaStore.objects.get(response=captcha, hashkey=captcha_id, expiration__gt=timezone.now()).delete()
        except CaptchaStore.DoesNotExist:
            return JsonResponse({'msg': '验证码错误'}, status=400)

        return JsonResponse({})

typeidea/typeidea/themes/bootstrap/templates/comment/block.html
<hr/>
<div class="comment">
    <form id="comment_form" class="form-group" action="/comment/" method="POST">
        {% csrf_token %}
        <input name="target" type="hidden" value="{{ target }}"/>
        {{ comment_form }}
        <div id="captcha_section"></div>
        <input id="verify" type="button" value="写好了!"/>
        <input id="submit" type="submit" style="display:None" value="写好了!"/>
    </form>

    <!-- 评论列表 -->
    <ul class="list-group">
        {% for comment in comment_list %}
        <li class="list-group-item">
            <div class="nickname">
                <a href="{{ comment.website }}">{{ comment.nickname }}</a> <span>{{ comment.created_time }}</span>
            </div>
            <div class="comment-content">
                {% autoescape off %}
                {{ comment.content }}
                {% endautoescape %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        var $form = $('.form-group');
        function init_captcha() {
            $.getJSON("{% url 'verify_captcha' %}", function(data) {
                $('#captcha_section').html(
                    '<img src="' + data.image_src +'" id="captcha_id" data-id="'+ data.captcha_id +'"/>' +
                    '<input id="captcha"/>'
                );
            })
        }
        $( document ).on( "click", '#captcha_id', init_captcha);

        $('#verify').on('click', function() {
            var captcha = $('#captcha').val();
            if (!captcha) {
                alert('验证码不能为空');
                return;
            }
            $.ajax({
                url: "{% url 'verify_captcha' %}",
                method: 'POST',
                data: {
                    'captcha_id': $('#captcha_id').data('id'),
                    'captcha': captcha,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function() {
                    $('#submit').click();
                    setTimeout(init_captcha, 500);
                },
                error: function(res, data) {
                    alert(res.responseJSON.msg);
                    return false;
                }
            });
        });

        init_captcha();
    });
</script>